import Head from "next/head";
import Image from "next/image";

import { Background, Navbar } from "@/components";
import { apecoin_round, apeicon } from "@/assets";
// import Navbar from "@/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <div className='absolute z-30 flex flex-row overflow-x-hidden mt-[65px] nav-height-screen w-full items-center px-[60px] justify-between'>
        <div className='flex flex-col items-center'>
          <p className='text-white mb-[30px] text-[30px] uppercase font-bold'>
            ENTER
          </p>

          <div>
            <label
              for='first_name'
              className='block mb-2 text-sm font-medium text-gray-900 dark:text-white'
            >
              Name
            </label>
            <input
              type='text'
              id='first_name'
              className='border text-sm rounded-lg block min-w-[250px] p-2.5 bg-gray-700 bg-opacity-0 dark:border-gray-600 placeholder-gray-500 text-white focus:outline-none'
              placeholder='John'
              required
            />
          </div>

          <div>
            <label
              for='website-admin'
              class='block mb-2 text-sm font-medium text-gray-900 dark:text-white mt-[15px]'
            >
              Username
            </label>

            <div class='flex'>
              <span class='inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border border-r-0 border-gray-300 rounded-l-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600'>
                @
              </span>
              <input
                type='text'
                id='website-admin'
                class='border text-sm rounded-tr-lg rounded-br-lg block min-w-[218px] p-2.5 bg-gray-700 bg-opacity-0 dark:border-gray-600 placeholder-gray-500 text-white focus:outline-none'
                placeholder='lucidjoy'
              />
            </div>
          </div>

          <button
            type='button'
            class='text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:outline-none shadow-lg dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 mt-[30px] w-[120px]'
          >
            Submit
          </button>
        </div>

        <div className=''>
          <Image src={apeicon} width={300} />
        </div>
      </div>

      <Background />
    </>
  );
}
